### ISSUE TITLE
nmea0183 library failed when tested

### ISSUE THREAD

**Issue by Rasbats** [leamas/opencpn-libs#3]
Was working locally moving survey_pi to a managed version. 
Tried to use the nmea0183 library instead of including the source files.
Had to revert to source files due to a couple of errors: parsenmea and writenmea (I think). 
No time to pursue this at the moment.

**Comment by leamas** [comment]
https://github.com/Rasbats/survey_pi/pull/4

**Comment by leamas** [comment]
This seems to not really be about opencpn-libs since this is yet not used in survey_pi.  Still, the issues with nmea0183 seems to be fixed in https://github.com/Rasbats/survey_pi/pull/4.

As for opencpn-libs, the missing sentences DBT and DPT are available also there.

So, all seems well. Closing, please re-open if need be.
